main: space.hugster.hide.DonutHide
name: DonutHide
author: Hugster
api-version: 1.20
version: 1.1
folia-supported: true
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.0
  - io.github.revxrsal:lamp.common:4.0.0-beta.19
  - io.github.revxrsal:lamp.bukkit:4.0.0-beta.19
depend:
  - TAB